name: Deploy to heroku web app (staging)

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Release staging web app
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_WEB_STAGING_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_APP_BASE: "packages/react-app"
          NEXT_PUBLIC_NETWORK_NAME: mumbai
          NEXT_PUBLIC_API_URL: https://drecruit-api-staging.herokuapp.com
      - name: Release staging API
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_STAGING_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_APP_BASE: "packages/backend"
          DB_URL: ${{secrets.DB_URL}}
          COOKIE_KEY: ${{secrets.COOKIE_KEY}}
          CERAMIC_SEED: ${{secrets.CERAMIC_SEED}}
